openapi: 3.0.3
info:
  title: FamilyTree Auth Service API
  version: 1.0.0
  description: API for user authentication, registration, and authorization.

servers:
  - url: http://localhost:8000
    description: Local development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        first_name:
          type: string
        last_name:
          type: string
        is_active:
          type: boolean
        roles:
          type: array
          items:
            type: string
        mfa_enabled:
          type: boolean
        linked_accounts:
          type: array
          items:
            type: object

    UserUpdateRequest:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string

    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        first_name:
          type: string
        last_name:
          type: string
      required:
        - email
        - password

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        token_type:
          type: string
          default: "bearer"

    GoogleLoginRequest:
      type: object
      properties:
        id_token:
          type: string
      required:
        - id_token

paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /login:
    post:
      summary: Login user and obtain tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Unauthorized - invalid credentials

  /login/google:
    post:
      summary: Google social login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoogleLoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'

  /assign_role:
    post:
      summary: Assign a role to a user
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
            format: email
        - name: role_name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Role assigned
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /refresh_token:
    post:
      summary: Refresh the access token
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Token refreshed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'

  /revoke_role:
    post:
      summary: Revoke a role from a user
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
            format: email
        - name: role_name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Role revoked
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /users/{user_id}:
    get:
      summary: Get user profile by ID
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User profile found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found

    put:
      summary: Update user profile by ID
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateRequest'
      responses:
        '200':
          description: User profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request
        '404':
          description: User not found
