openapi: 3.1.0
info:
  title: Extended Services for Community Genealogy Platform
  description: OpenAPI specification for additional services: Search, Audit, Media, Graph, Localization, Analytics, Admin.
  version: 1.0.0

paths:
  ###############################
  # Search & Discovery Service #
  ###############################
  /search/person:
    get:
      summary: Search for persons
      parameters:
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: birthDate
          schema:
            type: string
            format: date
        - in: query
          name: location
          schema:
            type: string
      responses:
        '200':
          description: List of matching persons

  ########################
  # Audit & History API #
  ########################
  /audit/logs:
    get:
      summary: Retrieve audit logs
      parameters:
        - in: query
          name: entityId
          schema:
            type: string
        - in: query
          name: entityType
          schema:
            type: string
        - in: query
          name: userId
          schema:
            type: string
      responses:
        '200':
          description: List of audit entries

  #############################
  # Media Storage Service API #
  #############################
  /media/upload:
    post:
      summary: Upload a file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                associatedPersonId:
                  type: string
      responses:
        '201':
          description: File uploaded

  /media/{mediaId}:
    get:
      summary: Retrieve media metadata
      parameters:
        - in: path
          name: mediaId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Media metadata

  ############################
  # Graph Query Service API #
  ############################
  /graph/traverse:
    post:
      summary: Traverse graph relationships
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                startPersonId:
                  type: string
                depth:
                  type: integer
                direction:
                  type: string
                  enum: [up, down, both]
      responses:
        '200':
          description: Graph traversal result

  #################################
  # Localization & Language API   #
  #################################
  /localization/translate:
    get:
      summary: Translate a term or phrase
      parameters:
        - in: query
          name: text
          schema:
            type: string
        - in: query
          name: lang
          schema:
            type: string
      responses:
        '200':
          description: Translated text

  ############################
  # Analytics & Insights API #
  ############################
  /analytics/usage:
    get:
      summary: Get user and activity stats
      responses:
        '200':
          description: Usage stats

  /analytics/top-contributors:
    get:
      summary: List top contributing users
      responses:
        '200':
          description: Contributor list

  ###########################
  # Admin & Moderation API #
  ###########################
  /admin/reports:
    get:
      summary: Get user-submitted reports
      responses:
        '200':
          description: List of reports

  /admin/users/{userId}/ban:
    post:
      summary: Ban a user
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User banned
