openapi: 3.0.3
info:
  title: Notification Service API
  version: 1.0.0
  description: API to manage user notifications.
servers:
  - url: https://api.example.com/notifications
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        type:
          type: string
        message:
          type: string
        data:
          type: object
          additionalProperties: true
        read:
          type: boolean
        created_at:
          type: string
          format: date-time
      required:
        - id
        - user_id
        - type
        - message
        - read
        - created_at
paths:
  /notifications:
    get:
      summary: Get notifications for a user
      security:
        - BearerAuth: []
      parameters:
        - name: unread_only
          in: query
          schema:
            type: boolean
          description: Filter unread notifications only
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: List of notifications
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Notification'
                  page:
                    type: integer
                  limit:
                    type: integer
                  total_records:
                    type: integer
                  total_pages:
                    type: integer

  /notifications/{id}/read:
    post:
      summary: Mark a notification as read
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Notification marked as read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '404':
          description: Notification not found
security:
  - BearerAuth: []
