# Docker Compose Development Override
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: "3.8"

services:
  # Frontend in development mode with hot reload
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    container_name: dzinza-frontend-dev
    ports:
      - "3000:3000" # Vite dev server port
    depends_on:
      - backend_service
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL="" # Use relative URLs with Vite proxy
      - VITE_API_TIMEOUT=30000
      - VITE_JWT_STORAGE_KEY=dzinza_access_token
      - VITE_REFRESH_TOKEN_KEY=dzinza_refresh_token
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent node_modules from being overwritten
    networks:
      - dzinza-network
    command: ["npm", "run", "dev"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Override frontend service to disable it in dev mode
  frontend:
    profiles: ["production"] # Only start in production profile
