apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: dzinza
  labels:
    app: auth-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
      version: v1
  template:
    metadata:
      labels:
        app: auth-service
        version: v1
    spec:
      containers:
        - name: auth-service
          image: dzinza/auth-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: PYTHON_APP_MODULE
              value: "app.main:app"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dzinza-secrets
                  key: db_password
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dzinza-secrets
                  key: redis_password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dzinza-secrets
                  key: jwt_secret
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: dzinza-secrets
                  key: jwt_refresh_secret
            - name: JWT_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: JWT_ALGORITHM
            - name: JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: JWT_AUDIENCE
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: SMTP_PORT
            - name: SMTP_USER
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: dzinza-secrets
                  key: smtp_pass
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: dzinza-secrets
                  key: google_client_id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dzinza-secrets
                  key: google_client_secret
            - name: OTEL_SERVICE_NAME
              value: "auth-service"
            - name: JAEGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: JAEGER_ENDPOINT
            - name: PYTHONUNBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: PYTHONUNBUFFERED
            - name: PYTHONDONTWRITEBYTECODE
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: PYTHONDONTWRITEBYTECODE
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: dzinza
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
