apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  namespace: dzinza
  labels:
    app: backend-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-service
      version: v1
  template:
    metadata:
      labels:
        app: backend-service
        version: v1
    spec:
      containers:
        - name: backend-service
          image: dzinza/backend-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: DEBUG
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: AUTH_SERVICE_URL
            - name: GENEALOGY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: GENEALOGY_SERVICE_URL
            - name: SEARCH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: SEARCH_SERVICE_URL
            - name: STORAGE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: STORAGE_SERVICE_URL
            - name: AUTH_SERVICE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: AUTH_SERVICE_URL
            - name: GENEALOGY_SERVICE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: GENEALOGY_SERVICE_URL
            - name: SEARCH_SERVICE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: SEARCH_SERVICE_URL
            - name: STORAGE_SERVICE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: STORAGE_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dzinza-secrets
                  key: jwt_secret
            - name: JWT_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: JWT_ALGORITHM
            - name: JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: JWT_AUDIENCE
            - name: OTEL_SERVICE_NAME
              value: "api-gateway"
            - name: JAEGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: JAEGER_ENDPOINT
            - name: PYTHONUNBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: PYTHONUNBUFFERED
            - name: PYTHONDONTWRITEBYTECODE
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: PYTHONDONTWRITEBYTECODE
            - name: API_V1_STR
              value: "/api/v1"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/gateway/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/gateway/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dzinza
  labels:
    app: backend-service
spec:
  selector:
    app: backend-service
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
