apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data-pvc
  namespace: dzinza
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-meta-pvc
  namespace: dzinza
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
  namespace: dzinza
data:
  garage.toml: |
    metadata_dir = "/var/lib/garage/meta"
    data_dir = "/var/lib/garage/data"

    replication_mode = "none"

    rpc_bind_addr = "0.0.0.0:3901"
    rpc_public_addr = "127.0.0.1:3901"
    rpc_secret = "1799bccfd7411 abbccc9a3f8c9157b3b38b91bb274e878b90df7954a1d1d1c4a"

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "0.0.0.0:39000"
    root_domain = ".s3.garage.localhost"

    [s3_web]
    bind_addr = "0.0.0.0:39001"
    root_domain = ".web.garage.localhost"
    index = "index.html"

    [admin]
    api_bind_addr = "0.0.0.0:39011"
    admin_token = "changeme"
    metrics_token = "changeme"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-service
  namespace: dzinza
  labels:
    app: garage-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage-service
      version: v1
  template:
    metadata:
      labels:
        app: garage-service
        version: v1
    spec:
      containers:
        - name: garage
          image: dxflrs/garage:v2.0.0
          ports:
            - containerPort: 39000
              name: s3-api
            - containerPort: 39001
              name: s3-web
            - containerPort: 39011
              name: admin
            - containerPort: 3901
              name: rpc
          volumeMounts:
            - name: garage-config
              mountPath: /etc/garage.toml
              subPath: garage.toml
            - name: garage-data
              mountPath: /var/lib/garage/data
            - name: garage-meta
              mountPath: /var/lib/garage/meta
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 39011
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 39011
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
      volumes:
        - name: garage-config
          configMap:
            name: garage-config
        - name: garage-data
          persistentVolumeClaim:
            claimName: garage-data-pvc
        - name: garage-meta
          persistentVolumeClaim:
            claimName: garage-meta-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: garage-service
  namespace: dzinza
  labels:
    app: garage-service
spec:
  selector:
    app: garage-service
  ports:
    - port: 39000
      targetPort: 39000
      name: s3-api
    - port: 39001
      targetPort: 39001
      name: s3-web
    - port: 39011
      targetPort: 39011
      name: admin
  type: ClusterIP
