apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: dzinza
  labels:
    app: search-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
      version: v1
  template:
    metadata:
      labels:
        app: search-service
        version: v1
    spec:
      containers:
        - name: search-service
          image: dzinza/search-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: DEBUG
            - name: PORT
              value: "8000"
            - name: ELASTICSEARCH_URL
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: ELASTICSEARCH_URL
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dzinza-secrets
                  key: elasticsearch_password
            - name: ELASTICSEARCH_INDEX_PERSONS
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: ELASTICSEARCH_INDEX_PERSONS
            - name: ELASTICSEARCH_INDEX_FAMILY_TREES
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: ELASTICSEARCH_INDEX_FAMILY_TREES
            - name: ELASTICSEARCH_INDEX_EVENTS
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: ELASTICSEARCH_INDEX_EVENTS
            - name: ELASTICSEARCH_REQUEST_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: ELASTICSEARCH_REQUEST_TIMEOUT
            - name: ELASTICSEARCH_MAX_RETRIES
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: ELASTICSEARCH_MAX_RETRIES
            - name: ELASTICSEARCH_RETRY_ON_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: ELASTICSEARCH_RETRY_ON_TIMEOUT
            - name: MONGODB_ANALYTICS_ENABLED
              value: "false"
            - name: MONGODB_URL_ANALYTICS
              value: "mongodb://$(DB_USER):$(MONGO_PASSWORD)@mongodb-service:27017/$(MONGODB_SEARCH_DB)?authSource=admin"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: DB_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dzinza-secrets
                  key: mongo_password
            - name: MONGODB_SEARCH_DB
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: MONGODB_SEARCH_DB
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dzinza-secrets
                  key: jwt_secret
            - name: JWT_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: JWT_ALGORITHM
            - name: JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: JWT_AUDIENCE
            - name: CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: CORS_ORIGINS
            - name: OTEL_SERVICE_NAME
              value: "search-service"
            - name: JAEGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: JAEGER_ENDPOINT
            - name: ENABLE_TRACING
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: ENABLE_TRACING
            - name: ENABLE_METRICS
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: ENABLE_METRICS
            - name: PYTHONUNBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: PYTHONUNBUFFERED
            - name: PYTHONDONTWRITEBYTECODE
              valueFrom:
                configMapKeyRef:
                  name: dzinza-config
                  key: PYTHONDONTWRITEBYTECODE
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: dzinza
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
