# Dzinza Genealogy Platform - Kubernetes Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: dzinza
  labels:
    app: dzinza-genealogy
    environment: production
    version: "1.0.0"
---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: dzinza-config
  namespace: dzinza
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  API_RATE_LIMIT: "100"
  MAX_FILE_SIZE: "10MB"
  CORS_ORIGIN: "https://dzinza.com,https://app.dzinza.com"
  BCRYPT_ROUNDS: "12"
---
# Secret for sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: dzinza-secrets
  namespace: dzinza
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  db-password: eW91cl9zZWN1cmVfcGFzc3dvcmQ=
  mongo-password: eW91cl9tb25nb19wYXNzd29yZA==
  redis-password: eW91cl9yZWRpc19wYXNzd29yZA==
  jwt-secret: eW91cl9qd3Rfc2VjcmV0X2tleQ==
  api-key: eW91cl9hcGlfa2V5
  aws-access-key: eW91cl9hd3NfYWNjZXNzX2tleQ==
  aws-secret-key: eW91cl9hd3Nfc2VjcmV0X2tleQ==
