from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from enum import Enum
import uuid # For user_ids

from app.models.base_model import BaseDocumentModel, PyObjectId

class MergeSuggestionStatus(str, Enum):
    PENDING = "pending"      # Awaiting review
    ACCEPTED = "accepted"    # Merge was approved and performed
    REJECTED = "rejected"    # Merge was reviewed and denied
    CANCELLED = "cancelled"  # Suggester cancelled it
    ERROR = "error"          # An error occurred during automated merge attempt

class SuggestedChangeDetail(BaseModel):
    field_name: str                 # e.g., "name_details.first_name", "birth.date_exact"
    current_value_person1: Optional[Any] = None
    current_value_person2: Optional[Any] = None
    suggested_value: Optional[Any] = None # Value to use after merge for this field
    resolution_strategy: Optional[str] = None # e.g., "use_person1", "use_person2", "combine", "custom"

class MergeSuggestionModel(BaseDocumentModel):
    family_tree_id: PyObjectId = Field(...)

    # The two persons being considered for merging
    person1_id: PyObjectId = Field(...)
    person1_name_preview: Optional[str] = None # Denormalized for display

    person2_id: PyObjectId = Field(...)
    person2_name_preview: Optional[str] = None # Denormalized for display

    # Details about why the merge is suggested (e.g., similarity score, matching fields)
    suggestion_reason: Optional[str] = Field(None, max_length=1000)
    similarity_score: Optional[float] = None # If generated by an algorithm (0.0 to 1.0)

    # Detailed field-by-field comparison and proposed merged values
    # This can be complex. For simplicity, it might just show differences
    # and the admin/user decides on the final values during the merge review UI.
    # A more advanced system might pre-populate suggested merged fields.
    suggested_changes: List[SuggestedChangeDetail] = Field(default_factory=list)

    status: MergeSuggestionStatus = Field(default=MergeSuggestionStatus.PENDING)

    # Who suggested the merge (system or a user)
    suggester_type: str = Field(default="system") # "system" or "user"
    suggester_user_id: Optional[uuid.UUID] = None # If suggested by a user

    # Who reviewed and actioned the merge
    reviewer_user_id: Optional[uuid.UUID] = None
    reviewed_at: Optional[datetime] = None
    reviewer_notes: Optional[str] = Field(None, max_length=1000)

    # If accepted, this might link to the new merged person ID (if one is created)
    # or indicate which person was kept and which was merged/deleted.
    merged_person_id: Optional[PyObjectId] = None # The ID of the person record that remains after merge
    archived_person_id: Optional[PyObjectId] = None # The ID of the person record that was merged into the other and archived/deleted

    class Config:
        # collection_name = "merge_suggestions"
        json_encoders = {
            **BaseDocumentModel.Config.json_encoders,
            MergeSuggestionStatus: lambda mss: mss.value,
        }
        # Pydantic v2: model_config = ConfigDict(use_enum_values=True)

from datetime import datetime # For reviewed_at type hint. Already in base_model.
