metadata_dir = "/var/lib/garage/meta1"
data_dir = "/var/lib/garage/data1"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 3
compression_level = 2

node_name = "node1"
rpc_bind_addr = "0.0.0.0:39011"
rpc_public_addr = "garage1:39011"
rpc_secret = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
bootstrap_peers = [
  "dzinza-garage2:39012",
  "dzinza-garage3:39013"
]

[s3_api]
s3_region = "garage1"
api_bind_addr = "0.0.0.0:39000"
root_domain = ".s3.garage"

[s3_web]
bind_addr = "0.0.0.0:39021"
root_domain = ".web.garage"
index = "index.html"
